# Generated by Django 3.2.8 on 2021-11-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(max_length=200, verbose_name='sous titre')),
                ('content', models.TextField(max_length=300, verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'A propos',
                'verbose_name_plural': 'A propos',
            },
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
