# Generated by Django 3.2.8 on 2021-11-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0002_auto_20211116_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
