# Generated by Django 3.2.8 on 2021-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media_root', verbose_name='Photo')),
                ('price', models.IntegerField(default=0, verbose_name='Prix')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
            },
        ),
    ]
